// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLtBlackip = "lt_blackip"

// LtBlackip mapped from table <lt_blackip>
type LtBlackip struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	IP         string `gorm:"column:ip;not null" json:"ip"`                   // IP地址
	Blacktime  int32  `gorm:"column:blacktime;not null" json:"blacktime"`     // 黑名单限制到期时间
	SysCreated int32  `gorm:"column:sys_created;not null" json:"sys_created"` // 创建时间
	SysUpdated int32  `gorm:"column:sys_updated;not null" json:"sys_updated"` // 修改时间
}

// TableName LtBlackip's table name
func (*LtBlackip) TableName() string {
	return TableNameLtBlackip
}
