// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLtCode = "lt_code"

// LtCode mapped from table <lt_code>
type LtCode struct {
	ID         int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	GiftID     int32  `gorm:"column:gift_id;not null" json:"gift_id"`         // 奖品ID，关联lt_gift表
	Code       string `gorm:"column:code;not null" json:"code"`               // 虚拟券编码
	SysCreated int32  `gorm:"column:sys_created;not null" json:"sys_created"` // 创建时间
	SysUpdated int32  `gorm:"column:sys_updated;not null" json:"sys_updated"` // 更新时间
	SysStatus  int32  `gorm:"column:sys_status;not null" json:"sys_status"`   // 状态，0正常，1作废，2已发放
}

// TableName LtCode's table name
func (*LtCode) TableName() string {
	return TableNameLtCode
}
