// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLtGift = "lt_gift"

// LtGift mapped from table <lt_gift>
type LtGift struct {
	ID           int32  `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	Title        string `gorm:"column:title;not null" json:"title"`                    // 奖品名称
	PrizeNum     int32  `gorm:"column:prize_num;not null;default:-1" json:"prize_num"` // 奖品数量，0 无限量，>0限量，<0无奖品
	LeftNum      int32  `gorm:"column:left_num;not null" json:"left_num"`              // 剩余数量
	PrizeCode    string `gorm:"column:prize_code;not null" json:"prize_code"`          // 0-9999表示100%，0-0表示万分之一的中奖概率
	PrizeTime    int32  `gorm:"column:prize_time;not null" json:"prize_time"`          // 发奖周期，D天
	Img          string `gorm:"column:img;not null" json:"img"`                        // 奖品图片
	Displayorder int32  `gorm:"column:displayorder;not null" json:"displayorder"`      // 位置序号，小的排在前面
	Gtype        int32  `gorm:"column:gtype;not null" json:"gtype"`                    // 奖品类型，0 虚拟币，1 虚拟券，2 实物-小奖，3 实物-大奖
	Gdata        string `gorm:"column:gdata;not null" json:"gdata"`                    // 扩展数据，如：虚拟币数量
	TimeBegin    int32  `gorm:"column:time_begin;not null" json:"time_begin"`          // 开始时间
	TimeEnd      int32  `gorm:"column:time_end;not null" json:"time_end"`              // 结束时间
	PrizeData    string `gorm:"column:prize_data" json:"prize_data"`                   // 发奖计划，[[时间1,数量1],[时间2,数量2]]
	PrizeBegin   int32  `gorm:"column:prize_begin;not null" json:"prize_begin"`        // 发奖计划周期的开始
	PrizeEnd     int32  `gorm:"column:prize_end;not null" json:"prize_end"`            // 发奖计划周期的结束
	SysStatus    int32  `gorm:"column:sys_status;not null" json:"sys_status"`          // 状态，0 正常，1 删除
	SysCreated   int32  `gorm:"column:sys_created;not null" json:"sys_created"`        // 创建时间
	SysUpdated   int32  `gorm:"column:sys_updated;not null" json:"sys_updated"`        // 修改时间
	SysIP        string `gorm:"column:sys_ip;not null" json:"sys_ip"`                  // 操作人IP
}

// TableName LtGift's table name
func (*LtGift) TableName() string {
	return TableNameLtGift
}
