// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

const TableNameLtUserday = "lt_userday"

// LtUserday mapped from table <lt_userday>
type LtUserday struct {
	ID         int32 `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	UID        int32 `gorm:"column:uid;not null" json:"uid"`                 // 用户ID
	Day        int32 `gorm:"column:day;not null" json:"day"`                 // 日期，如：20180725
	Num        int32 `gorm:"column:num;not null" json:"num"`                 // 次数
	SysCreated int32 `gorm:"column:sys_created;not null" json:"sys_created"` // 创建时间
	SysUpdated int32 `gorm:"column:sys_updated;not null" json:"sys_updated"` // 修改时间
}

// TableName LtUserday's table name
func (*LtUserday) TableName() string {
	return TableNameLtUserday
}
